# Název workflow
name: Spustit PageSpeed Test a uložit do BigQuery

on:
  workflow_dispatch:
  schedule:
    - cron: '0 1 * * 0' # Každou neděli v 1:00 UTC

jobs:
  run-pagespeed-test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout kódu
        uses: actions/checkout@v4

      - name: Nastavení Python 3.10
        uses: actions/setup-python@v5
        with:
          python-version: '3.10'

      - name: Instalace závislostí
        run: |
          python -m pip install --upgrade pip
          pip install requests google-cloud-bigquery

      - name: Autentizace do Google Cloud
        id: auth
        uses: 'google-github-actions/auth@v2'
        with:
          credentials_json: ${{ secrets.GCP_SA_KEY }}

      - name: Spuštění PageSpeed testu
        env:
          PAGESPEED_API_KEY: ${{ secrets.PAGESPEED_API_KEY }}
          BIGQUERY_TABLE_ID: ${{ secrets.BIGQUERY_TABLE_ID }}
          URLS_TO_TEST: ${{ vars.URLS_TO_TEST }}
          GOOGLE_APPLICATION_CREDENTIALS: ${{ steps.auth.outputs.credentials_file_path }}
        run: |
          python pagespeedInsightsAPI.py