# Název workflow
name: Spustit PageSpeed Test a uložit do BigQuery

on:
  workflow_dispatch:
  schedule:
    - cron: '0 1 * * 0' # Každou neděli v 1:00 UTC

jobs:
  run-pagespeed-test:
    runs-on: ubuntu-latest

    steps:
      # Krok 1: Stáhne kód repozitáře
      - name: Checkout kódu
        uses: actions/checkout@v4

      # Krok 2: Nastaví Python
      - name: Nastavení Python 3.10
        uses: actions/setup-python@v5
        with:
          python-version: '3.10'

      # Krok 3: Instalace Python knihoven (přidána google-cloud-bigquery)
      - name: Instalace závislostí
        run: |
          python -m pip install --upgrade pip
          pip install requests google-cloud-bigquery

      # KROK 4: (NOVÝ) Autentizace do Google Cloud
      # Použije secret GCP_SA_KEY k přihlášení
      - name: Autentizace do Google Cloud
        id: auth
        uses: 'google-github-actions/auth@v2'
        with:
          credentials_json: ${{ secrets.GCP_SA_KEY }}

      # Krok 5: Spuštění Python skriptu
      - name: Spuštění PageSpeed testu
        env:
          # Předání všech tří secretů do prostředí skriptu
          PAGESPEED_API_KEY: ${{ secrets.PAGESPEED_API_KEY }}
          BIGQUERY_TABLE_ID: ${{ secrets.BIGQUERY_TABLE_ID }}
          # Následující řádek je technicky potřeba pro BQ klienta,
          # ale 'google-github-actions/auth' ho nastaví automaticky.
          # Pro jistotu ho můžeme nastavit explicitně z výstupu kroku 'auth':
          GOOGLE_APPLICATION_CREDENTIALS: ${{ steps.auth.outputs.credentials_file_path }}
        run: |
          # Spustíme skript s novým názvem
          python pagespeedInsightsAPI.py
